// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: host/workspace.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "../../../bufbuild/protobuf/wire";

export interface GetWorkspacePathsRequest {
  /**
   * The unique ID for the workspace/project.
   * This is currently optional in vscode. It is required in other environments where cline is running at
   * the application level, and the user can open multiple projects.
   */
  id?: string | undefined;
}

export interface GetWorkspacePathsResponse {
  /** The unique ID for the workspace/project. */
  id?: string | undefined;
  paths: string[];
}

export interface SaveOpenDocumentIfDirtyRequest {
  filePath?: string | undefined;
}

export interface SaveOpenDocumentIfDirtyResponse {
  /** Returns true if the document was saved. */
  wasSaved?: boolean | undefined;
}

function createBaseGetWorkspacePathsRequest(): GetWorkspacePathsRequest {
  return { id: undefined };
}

export const GetWorkspacePathsRequest: MessageFns<GetWorkspacePathsRequest> = {
  encode(message: GetWorkspacePathsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWorkspacePathsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkspacePathsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWorkspacePathsRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : undefined };
  },

  toJSON(message: GetWorkspacePathsRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWorkspacePathsRequest>, I>>(base?: I): GetWorkspacePathsRequest {
    return GetWorkspacePathsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWorkspacePathsRequest>, I>>(object: I): GetWorkspacePathsRequest {
    const message = createBaseGetWorkspacePathsRequest();
    message.id = object.id ?? undefined;
    return message;
  },
};

function createBaseGetWorkspacePathsResponse(): GetWorkspacePathsResponse {
  return { id: undefined, paths: [] };
}

export const GetWorkspacePathsResponse: MessageFns<GetWorkspacePathsResponse> = {
  encode(message: GetWorkspacePathsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      writer.uint32(10).string(message.id);
    }
    for (const v of message.paths) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWorkspacePathsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkspacePathsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.paths.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetWorkspacePathsResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : undefined,
      paths: globalThis.Array.isArray(object?.paths) ? object.paths.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: GetWorkspacePathsResponse): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = message.id;
    }
    if (message.paths?.length) {
      obj.paths = message.paths;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetWorkspacePathsResponse>, I>>(base?: I): GetWorkspacePathsResponse {
    return GetWorkspacePathsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetWorkspacePathsResponse>, I>>(object: I): GetWorkspacePathsResponse {
    const message = createBaseGetWorkspacePathsResponse();
    message.id = object.id ?? undefined;
    message.paths = object.paths?.map((e) => e) || [];
    return message;
  },
};

function createBaseSaveOpenDocumentIfDirtyRequest(): SaveOpenDocumentIfDirtyRequest {
  return { filePath: undefined };
}

export const SaveOpenDocumentIfDirtyRequest: MessageFns<SaveOpenDocumentIfDirtyRequest> = {
  encode(message: SaveOpenDocumentIfDirtyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filePath !== undefined) {
      writer.uint32(18).string(message.filePath);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SaveOpenDocumentIfDirtyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveOpenDocumentIfDirtyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SaveOpenDocumentIfDirtyRequest {
    return { filePath: isSet(object.filePath) ? globalThis.String(object.filePath) : undefined };
  },

  toJSON(message: SaveOpenDocumentIfDirtyRequest): unknown {
    const obj: any = {};
    if (message.filePath !== undefined) {
      obj.filePath = message.filePath;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SaveOpenDocumentIfDirtyRequest>, I>>(base?: I): SaveOpenDocumentIfDirtyRequest {
    return SaveOpenDocumentIfDirtyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SaveOpenDocumentIfDirtyRequest>, I>>(
    object: I,
  ): SaveOpenDocumentIfDirtyRequest {
    const message = createBaseSaveOpenDocumentIfDirtyRequest();
    message.filePath = object.filePath ?? undefined;
    return message;
  },
};

function createBaseSaveOpenDocumentIfDirtyResponse(): SaveOpenDocumentIfDirtyResponse {
  return { wasSaved: undefined };
}

export const SaveOpenDocumentIfDirtyResponse: MessageFns<SaveOpenDocumentIfDirtyResponse> = {
  encode(message: SaveOpenDocumentIfDirtyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.wasSaved !== undefined) {
      writer.uint32(8).bool(message.wasSaved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SaveOpenDocumentIfDirtyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveOpenDocumentIfDirtyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.wasSaved = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SaveOpenDocumentIfDirtyResponse {
    return { wasSaved: isSet(object.wasSaved) ? globalThis.Boolean(object.wasSaved) : undefined };
  },

  toJSON(message: SaveOpenDocumentIfDirtyResponse): unknown {
    const obj: any = {};
    if (message.wasSaved !== undefined) {
      obj.wasSaved = message.wasSaved;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SaveOpenDocumentIfDirtyResponse>, I>>(base?: I): SaveOpenDocumentIfDirtyResponse {
    return SaveOpenDocumentIfDirtyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SaveOpenDocumentIfDirtyResponse>, I>>(
    object: I,
  ): SaveOpenDocumentIfDirtyResponse {
    const message = createBaseSaveOpenDocumentIfDirtyResponse();
    message.wasSaved = object.wasSaved ?? undefined;
    return message;
  },
};

/** Provides methods for working with workspaces/projects. */
export type WorkspaceServiceDefinition = typeof WorkspaceServiceDefinition;
export const WorkspaceServiceDefinition = {
  name: "WorkspaceService",
  fullName: "host.WorkspaceService",
  methods: {
    /** Returns a list of the top level directories of the workspace. */
    getWorkspacePaths: {
      name: "getWorkspacePaths",
      requestType: GetWorkspacePathsRequest,
      requestStream: false,
      responseType: GetWorkspacePathsResponse,
      responseStream: false,
      options: {},
    },
    /**
     * Saves an open document if it's open in the editor and has unsaved changes.
     * Returns true if the document was saved, returns false if the document was not found, or did not
     * need to be saved.
     */
    saveOpenDocumentIfDirty: {
      name: "saveOpenDocumentIfDirty",
      requestType: SaveOpenDocumentIfDirtyRequest,
      requestStream: false,
      responseType: SaveOpenDocumentIfDirtyResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
