// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: host/env.proto

/* eslint-disable */
import { Empty, EmptyRequest, String, StringRequest } from "../cline/common";

/** Provides methods for working with the user's environment. */
export type EnvServiceDefinition = typeof EnvServiceDefinition;
export const EnvServiceDefinition = {
  name: "EnvService",
  fullName: "host.EnvService",
  methods: {
    /** Writes text to the system clipboard. */
    clipboardWriteText: {
      name: "clipboardWriteText",
      requestType: StringRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {},
    },
    /** Reads text from the system clipboard. */
    clipboardReadText: {
      name: "clipboardReadText",
      requestType: EmptyRequest,
      requestStream: false,
      responseType: String,
      responseStream: false,
      options: {},
    },
  },
} as const;
