// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/slash.proto
/* eslint-disable */
import { Empty, StringRequest } from "./common";
export const SlashServiceDefinition = {
    name: "SlashService",
    fullName: "cline.SlashService",
    methods: {
        /** Sends button click message */
        reportBug: {
            name: "reportBug",
            requestType: StringRequest,
            requestStream: false,
            responseType: Empty,
            responseStream: false,
            options: {},
        },
        condense: {
            name: "condense",
            requestType: StringRequest,
            requestStream: false,
            responseType: Empty,
            responseStream: false,
            options: {},
        },
    },
};
